stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building Docker image..."
    - docker build -t myapp:latest ./Docker/prod
deploy:
  stage: deploy
  image: appleboy/drone-ssh
  script:
    - echo "$SSH_PRIVATE_KEY" > private_key
    - chmod 600 private_key
    - ssh -i private_key -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull myapp:latest && docker-compose up -d"
  only:
    - main

