services:
  backend:
    build:
      context: ../..
      dockerfile: Docker/prod/Dockerfile
      args:
        SERVICE: start:server
    image: enersave-prod-backend
    container_name: enersave-prod-backend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
      - PORT=80
    env_file:
      - .env
    volumes:
      - ../../:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ../..
      dockerfile: Docker/prod/Dockerfile
      args:
        SERVICE: start:client
    image: enersave-prod-frontend
    container_name: enersave-prod-frontend
    ports:
      - "443:443"
    environment:
      - NODE_ENV=development
      - PORT=443
      - API_URL=http://enersave-prod-backend/api
    env_file:
      - .env
    volumes:
      - ../../:/usr/src/app
      - /usr/src/app/node_modules